version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graphqlcrud
      MYSQL_USER: graphql
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
